[build]
  publish = "public"
  functions = "func"
  command = "npm run build"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[build.processing]
  html = { pretty_urls = true }

[functions]
  node_bundler = "esbuild"

[template.environment]
  DISCORD_CLIENT_ID = "Your Discord App's client ID"
  DISCORD_CLIENT_SECRET = "Your Discord App's client secret"
  DISCORD_BOT_TOKEN = "Your Discord Bot Token"
  GUILD_ID = "ID of the guild this deployment targets"
  APPEALS_CHANNEL = "ID of the channel used for appeal form submission"
  JWT_SECRET = "JSON Web Token secret, mash keyboard plz"
